site_name: KIB in Batch project
theme:
  name: material 
nav:
  - Home: index.md
  - Introduction: intro.md
  - KIB in Batch: kib-in-batch.md
  - KIB in Batch POSIX API: kib-in-batch-posix-api.md
  - KIB in Batch Package Management: kib-in-batch-package-management.md
  - KIBDock: kibdock.md
  - Tweets: tweets.html
  - Blog:
    - Bots are copying random GitHub repos: blog/bots-001.md
    - Warp Terminal is not a proper terminal: blog/warp-002.md
