site_name: KIB in Batch project
theme:
  name: material
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Introduction: intro.md
  - KIB in Batch: kib-in-batch.md
  - KIB in Batch POSIX API: kib-in-batch-posix-api.md
  - KIB in Batch Package Management: kib-in-batch-package-management.md
  - KIBDock: kibdock.md
  - Blog:
      - Bots are copying random GitHub repos: blog/bots-001.md
      - Warp Terminal is not a proper terminal: blog/warp-002.md
